name: just_another_workout_timer
description: Just Another Workout Timer

version: 1.11.2+20220317

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: 3.6.3
  path_provider: 2.0.12
  flutter_file_dialog: 3.0.0
  pref: 2.7.1
  fluttertoast: 8.1.2
  prefs: 4.0.0
  url_launcher: 6.1.8
  wakelock: 0.6.2
  soundpool: 2.3.0
  intl_utils: 2.8.1
  json_annotation: 4.8.0
  flutter_phoenix: 1.1.0
  flutter_native_splash: 2.2.17
  scrollable_positioned_list: 0.3.5
  flutter_localizations:
    sdk: flutter
  uuid: 3.0.7
  flutter_nord_theme: 2.1.0
  share_plus: 6.3.0
  provider: 6.0.5

dev_dependencies:
  flutter_launcher_icons: 0.11.0
  flutter_oss_licenses: 2.0.1
  json_serializable: 6.6.1
  build_runner: 2.3.3
  flutter_lints: 2.0.1

dependency_overrides: 
  image: ^4.0.10

flutter:
  uses-material-design: true
  generate: false
  assets:
    - LICENSE
    - assets/beep_low.wav
    - assets/beep_high.wav
    - assets/tick.wav

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/ic_launcher.png"

flutter_intl:
  enabled: true

flutter_native_splash:
  color: "#D8DEE9"
  color_dark: "#2E3440"
  image: "assets/ic_launcher.png"
  fullscreen: true
  android_gravity: center
  android: true
  ios: false
  web: false
  android12: true
