name: just_another_workout_timer
description: Just Another Workout Timer

version: 1.11.2+20220317

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: 3.3.3
  path_provider: 2.0.10
  flutter_file_dialog: 2.3.0
  pref: 2.6.0
  fluttertoast: 8.0.9
  prefs: 3.5.0
  url_launcher: 6.1.2
  wakelock: 0.6.1+2
  soundpool: 2.3.0
  intl_utils: 2.6.1
  json_annotation: 4.5.0
  flutter_phoenix: 1.0.0
  flutter_native_splash: 2.1.6
  scrollable_positioned_list: 0.3.2
  flutter_localizations:
    sdk: flutter
  uuid: 3.0.6

dev_dependencies:
  flutter_launcher_icons: 0.9.2
  flutter_oss_licenses: 2.0.0+1
  effective_dart: 1.3.2
  json_serializable: 6.2.0
  build_runner: 2.1.10

flutter:
  uses-material-design: true
  generate: true
  assets:
    - LICENSE
    - assets/beep_low.wav
    - assets/beep_high.wav
    - assets/tick.wav

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/ic_launcher.png"

flutter_intl:
  enabled: true

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#303030"
  image: "assets/ic_launcher.png"
  fullscreen: true
  android_gravity: center
  android: true
  ios: false
  web: false
  android12: true
